PATH_COURSE_LECTURE="course/lecture/"
PATH_COURSE_DOCUMENT="course/document/"
PATH_COURSE_IMAGE="course/image/"
PATH_COURSE_VIDEO="course/video/"

module.exports={PATH_COURSE_LECTURE, PATH_COURSE_DOCUMENT, PATH_COURSE_IMAGE, PATH_COURSE_VIDEO}