const StatusMessage = {
  REQUEST_SUCCESS: "REQUEST SUCCESS",
  DATA_NOT_FOUND: "REQUEST SUCCESS! NOT FOUND ANY DATA",
  DATA_NOT_MAP: "REQUEST FAILURE! DATA NOT MAPPING",
  NOT_IMPLEMENTED: "REQUEST FAILURE! RESOURCE, FEATURE DOES NOT EXIST",
  DATA_CONFLICT: "REQUEST SUCCESS! DATA ALREADY EXISTS",
  NOT_PERMISSION: "ACCESS DENIED",
};


module.exports = {StatusMessage}
